name: Build

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
    paths-ignore:
      - "**.md"
      - LICENSE-Apache
      - LICENSE-MIT
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE-Apache
      - LICENSE-MIT

jobs:
  check:
    name: Type checking (Rust ${{ matrix.version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - "1.36"
          - "1.37"
          - "1.38"
          - "1.39"
          - "1.40"
          - "1.41"
          - "1.42"
          - "1.43"
          - "1.44"
          - "1.45"
          - "1.46"
          - "1.47"
          - "1.48"
          - "1.49"
          - "1.50"
          - "1.51"
          - "1.52"
          - "1.53"
          - "1.54"
          - "1.55"
          - "1.56"
          - "1.57"
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.version }}

      - name: Install cargo-hack
        shell: bash
        run: |
          host=$(rustc -Vv | grep host | sed 's/host: //')
          if [[ $host =~ windows ]]; then
              curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-${host}.zip -o cargo-hack.zip
              7z x cargo-hack.zip -o$HOME/.cargo/bin
          elif [[ $host =~ darwin|linux ]]; then
              curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-${host}.tar.gz | tar xzf - -C ~/.cargo/bin
          else
              echo "unsupported operating system"
              exit 1
          fi

      - name: Check powerset
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: |
            check
            --feature-powerset
            --exclude-features default
            --exclude-no-default-features

  check-embedded:
    name: Type checking on embedded (Rust ${{ matrix.version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "1.36"
          - "1.37"
          - "1.38"
          - "1.39"
          - "1.40"
          - "1.41"
          - "1.42"
          - "1.43"
          - "1.44"
          - "1.45"
          - "1.46"
          - "1.47"
          - "1.48"
          - "1.49"
          - "1.50"
          - "1.51"
          - "1.52"
          - "1.53"
          - "1.54"
          - "1.55"
          - "1.56"
          - "1.57"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.version }}
          target: thumbv7em-none-eabihf
          override: true

      - name: Install cargo-hack
        shell: bash
        run: |
          curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin

      - name: Check powerset
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: |
            check
            --feature-powerset
            --exclude-features default,std
            --exclude-no-default-features
            --target thumbv7em-none-eabihf

  fmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run `cargo fmt -- --check`
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
